### ISSUE TITLE
[request] "Settings menu" demo

### ISSUE THREAD

**Issue by puzrin** [littlevgl/lv_apps#1]
A lot of small embedded devices have interface like this:

1. Main screen
2. Settings menu with tons of params (mostly numeric, sometime text)

IMHO it would save a lot of time, if everyone could take ready example, and copy-paste code with controls of required type.

What is expected from menu:

- Good design
- Proper interaction with different input devices (touch/buttons)
- Code blocks for popular controls, ready to copy-paste
  - Example: "need to set speed between [1.0 ... 5.0] m/sec with step 0.1"

**Comment by puzrin** [comment]
Comments about current settings menu demo state:

- No instructions how to run demo. This [readme](https://github.com/littlevgl/lv_apps/blob/master/src/lv_settings/README.md) is for developpers, not for person who need just run demo to write comments about styles.
- Hardcoded paths. It will be problem to run this in PIO. Such problem was solved once in `lv_driver`.
- If animated gifs in `misc` are actual - those diverges significantly from what i posted.

**Comment by kisvegabor** [comment]
> No instructions how to run demo. This readme is for developpers, not for person who need just run demo to write comments about styles.

Updated. See https://github.com/littlevgl/lv_apps/commit/0e44f9ddd7758034d5ca3f6b0e9e5d2efb3d5270

> Hardcoded paths. It will be problem to run this in PIO. Such problem was solved once in lv_driver.

Updated. See https://github.com/littlevgl/lv_apps/commit/de937f284bc517e72d64eaefd3cb37b388c4c082

> If animated gifs in misc are actual - those diverges significantly from what i posted.

There are not for demonstration purpose but really they are the current items.
They really didn't have exactly the same styling as you proposed. However, they use LittlevGL themes which allows to simply change the overall styling. Regarding different font sizes, right now the themes support only one font, so it's the user's task to further customize the items as he needs. The current implementation
- looks well enough (no generic solution can be perfect for everybody)
- easy to change the overall styling with one line of code
- clean, easy to extend and modify 

If you have conceptual remarks about item types (such as missing item type, or different layout for an item type) I'd be curious about it.

**Comment by puzrin** [comment]
> They really didn't have exactly the same styling as you proposed.

From my point of view, that's a principal moment. Looks like you offer 20% of been done, and suggest user to make 80% of the rest :). I don't know how useful can this be, but that's certainly not what i suggested when created issue.

I can help only with following known style guides (material design, for example). But demo should have appropriate look. Because for feedback i need to play with real samples, not with something imagined.

**Comment by kisvegabor** [comment]
For me, it seems like the exact opposite. I implemented
- an engine to create/load menu pages
- an "API" to easily create menus
- added real-life items
- made it work with keyboard
- made it work with themes to easily change the styling
- the code is commented, well structured and easy to read and modify

What's left
- if you don't like something as it is, you need to customize it.

The first part is hardly only 20%. It's rather 90%. E.g. adding a bigger font to the "number set" item's value is not a big deal compared to the overall complexity

.

**Comment by puzrin** [comment]
I have no experience how to use code as criteria of interface usability :). This was a root of initial request - provide a demo with modern (useable) look. I know only one criteria for such tasks - interface should look as expected, first. Everything else is secondary. If you wish to do something else - no problem, but i can not help with it.

PS. If you think, the rest of work is 10% why not do it with other demo code? That will significantly reduce confusion.

**Comment by kisvegabor** [comment]
>  If you think, the rest of work is 10% why not do it with other demo code? That will significantly reduce confusion.

I'm planning to modernize the other apps too. 
Thanks to your screenshots, the settings app was created with usability in mind and got a good look and feel. The rest 10% is,  IMO,  application/user/project specific. 

I'm not planning to exactly copy the screenshots. But please tell what are your main concerns and we will see what could be improved.

**Comment by puzrin** [comment]
> I'm not planning to exactly copy the screenshots. But please tell what are your main concerns and we will see what could be improved.

IMO that would be not productive. Main concern is, that demo does not follows MD style guide, and naming it as MD add more confusion. Until general problem exists, it would be not rationale to fall into smaller details.

I don't know how to explain this short, and see 3 possible resolutions:

- You can spend a lot of time to read MD docs, design patterns and so on, to get own experience what is difference between MD and "hand made".
- If you trust me, you can take my screenshot and implement those exactly, pixel-to-pixel.
- You can declare that demo is about settings only, but not about MD (so this will be "yet another hand made style")

If you use my screenshots - i can participate. Other cases are not optimal from my point of view (in terms of value/time).

**Comment by kisvegabor** [comment]
I've read the MD guide when created the material theme and created the styles according to it. In the [official guide](https://material.io/) a [Menu](https://material.io/design/components/menus.html), a [Slider](https://material.io/design/components/sliders.html) and a [Button](https://material.io/design/components/buttons.html) looks like this:

![image](https://user-images.githubusercontent.com/7599318/62714982-da31b300-b9ff-11e9-9a3b-46001f9349df.png)


![image](https://user-images.githubusercontent.com/7599318/62714957-cdad5a80-b9ff-11e9-9da9-686063dafa3f.png)


![image](https://user-images.githubusercontent.com/7599318/62714920-bf5f3e80-b9ff-11e9-8d52-3eb2f58ecad7.png)


And they look like this in LittelvGL by default:
![image](https://user-images.githubusercontent.com/7599318/62714790-81621a80-b9ff-11e9-93c2-312015689bdd.png)

Code to reproduce:
```c
lv_theme_set_current(lv_theme_material_init(265, NULL));

lv_obj_t * obj = lv_list_create(lv_scr_act(), NULL);
lv_obj_set_width(obj, 150);
lv_obj_set_pos(obj, 20, 20);        
lv_cont_set_fit2(obj, LV_FIT_NONE, LV_FIT_TIGHT);
lv_list_add_btn(obj, NULL, "Item 1");
lv_list_add_btn(obj, NULL, "Item 2");
lv_list_add_btn(obj, NULL, "Item 3");
lv_list_add_btn(obj, NULL, "Item 4");

obj = lv_slider_create(lv_scr_act(), NULL);
lv_obj_set_size(obj, 150, 20);
lv_obj_set_pos(obj, 200, 20);

obj = lv_btn_create(lv_scr_act(), NULL);
lv_btn_set_fit(obj, LV_FIT_TIGHT);
lv_obj_set_pos(obj, 200, 50);

obj = lv_label_create(obj, NULL);
lv_label_set_text(obj, "BUTTON");
```

So I don't really know what the big problem is here. The user can give Material look to his UI with one line of code. 
- Does it perfectly follow the guide? No. There are limitations of LittlevGL and a generic solution can't fit every application. 
- Is it something good to get started? Definitely yes. User can finetune it as he needs, but it's already quite "Material-ish" (as you can see on the above images)

I'm sure that you are not interested in other themes, so just for completness:
by changing
`lv_theme_set_current(lv_theme_material_init(265, NULL));` 
to 
`lv_theme_set_current(lv_theme_night_init(265, NULL));`
the result:
![image](https://user-images.githubusercontent.com/7599318/62715501-eec27b00-ba00-11e9-8f3e-49bc6d6db55b.png)

**Comment by puzrin** [comment]
> So I don't really know what the big problem is here. The user can give Material look to his UI with one line of code.

Problem is, that you think lot of minor differences are ok (probably, because you are not designer). But those form style, and final result is very "intermediate". It may be good for first "wow-effect", but that's not MD. If you have designer at your work - ask his/her opinion.

- `menu` is for dropdowns, top level should be two-lines list (full screen) https://material.io/design/components/lists.html
  - separators should not be used
  - no embedded controls (except checkbox, may be)
  - in your sample of list, second line should be gray, not blue, also font sizes should be different.
- Button has too big rounding
- Slider line too fat
- Top bar should have background (now only button has it)
- No second-level screens to change values (attempt to embed into list breaks list look and cause bad interaction)

> Does it perfectly follow the guide? No. There are limitations of LittlevGL and a generic solution can't fit every application.

You can not follow style guide "partially". That's like with porting library - ported code should be exact, or it can not be named as port (because can not reuse existing docs and so on).

Problem is not with custom application demands, but with not following style guide. My screenshots are universal for any applications without typing text. I strongly disagree with approach, when result should depend on library features. That replaces real goal with something unpredictable.

IMHO correct approach is to implement exact style (with any kludges), and then consider how to organize it on second pass (extend api or something else).

[Evolutionary prototyping](https://en.wikipedia.org/wiki/Software_prototyping#Evolutionary_prototyping) approach works very well for such kind of tasks. For example, first attempt can be without animation, without some nested things, but top level should be exact as in MD style guide. Then add more details and so on.

**Comment by kisvegabor** [comment]
I agree the details are important, however, to be honest, I'm happy with the current result and not planning to improve it now. 

If you feel these improvements are really important please update the theme as you wish and send a  PR.

**Comment by puzrin** [comment]
> If you feel these improvements are really important please update the theme as you wish and send a PR.

Probability of this is low for 2 reasons:

- It's not comfortable for me to work with this repo (prefer PIO).
- I'm not limited with C and prefer use some CPP features.

So, i could do some fixes if more complete skeleton exists, or explain required changes, but i don't plan to be involved into more deep library development. The only constructive thing i could suggest in current situation - provide link to my app when it's ready. But i don't know how useful it will be, and that will be not soon.

Anyway, i can not advice you how to spend your time. Let's try another things. We still have pending tail of task we can to together (compressed fonts and so on).

**Comment by kisvegabor** [comment]
You can simply copy the files of the settigns app to make some experiments in PIO if it's more convenient.  

Anyway, I have some other things to do now, but I haven't forgotten the font decompression.

**Comment by kisvegabor** [comment]
As the settings app is added I close this issue.

Thank you very much for your contribution.

**Comment by PetrenkoIgor** [comment]
> I've started to work on it [here](https://github.com/littlevgl/lv_apps/blob/master/src/lv_settings/lv_settings.c).
> 
> I've implemented the engine of the settings.
> 
> What is working:
> 
> * Has the intended layout
> * [High level definition](https://github.com/littlevgl/lv_apps/blob/e53b9fa3dd0fc217623cb1564875a0191e5d2d48/src/lv_settings/lv_settings.c#L47-L67) of menus
> * Multi level menus
> * Naviagtion
> * No memory leak
> 
> What is still required:
> 
> * Animations
> * Styling
> * Some special menus with slider, roller, etc
> 
> ![settings1](https://user-images.githubusercontent.com/7599318/61801848-c72fb800-ae2f-11e9-8b3a-8f1ce4873557.gif)

How add icon?

**Comment by kisvegabor** [comment]
It's not supported now.

**Comment by PetrenkoIgor** [comment]
Ok. Thanks.
